export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const COMPLETE_ALL_TASKS = 'COMPLETE_ALL_TASKS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CLEAR_COMPLETED_TASKS = 'CLEAR_COMPLETED_TASKS';
